project:
  type: website
  output-dir: docs
website:
  site-url: "https://abu85.github.io/git-github-workshop/"
  description: "version control"
  favicon: "images/favicon.ico"

  navbar:
    background: primary
    pinned: true
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Precourse"
        href: ./scripts/00_precourse.html
      - text: "Episodes"
        menu:
          - text: "01 - Git Basics"
            href: episodes/01-basics.qmd
          - text: "02 - Setup"
            href: episodes/02-setup.qmd
          - text: "03 - Create Repo"
            href: episodes/03-create.qmd
          - text: "04 - Track Changes"
            href: episodes/04-changes.qmd
          - text: "05 - History"
            href: episodes/05-history.qmd
          - text: "06 - Ignore Files"
            href: episodes/06-ignore.qmd
          - text: "07 - GitHub"
            href: episodes/07-github.qmd
          - text: "08 - Collaboration"
            href: episodes/08-collab.qmd
          - text: "09 - Conflict Resolution"
            href: episodes/09-conflict.qmd
          - text: "10 - Open Source"
            href: episodes/10-open.qmd
          - text: "11 - Licensing"
            href: episodes/11-licensing.qmd
          - text: "12 - Citation"
            href: episodes/12-citation.qmd
          - text: "13 - Hosting"
            href: episodes/13-hosting.qmd
          - text: "14 - RStudio Tips"
            href: episodes/14-supplemental-rstudio.qmd
    right:
      - icon: envelope
        href: mailto:abu.siddique@slu.se

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    code-copy: true
    code-overflow: wrap
    highlight-style: github

metadata-files:
  - config.yaml
